FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
RUN set -x \
   # Missing https for some magic reason
   && apk add --no-cache --update ca-certificates \
   && apk add --virtual .build-dependencies wget \
   && apk add nginx-mod-http-lua \
   # Cleanup packages
   && apk del --purge .build-dependencies
